#include <wiringPi.h>
#include <softTone.h>
#include <stdio.h>
#include "tones.h"
#include "channels.h"

const int bpm = 120 / 4; // CS FS       A3[ ]*, D4[ ]*, F4S[ ]*, D4[ ]*, B3[ ]*, D4[ ]*, F4S[ ]*, D4[ ]*                                                                                                                                                                                                                                                                                                                                                                                                                                   CS FS BF                        BF                                                                                              A3[ ]*, C4[ ]*, F4[ ]*, C4[ ]*, A3[ ]*, C4[ ]*, F4[ ]*, C4[ ]*                                                                      BF CS FS                                                              CS FS                       A3[ ]*, D4[ ]*, F4S[ ]*, D4[ ]*, B3[ ]*, D4[ ]*, F4S[ ]*, D4                                                                                                                                                                                                                                                                                                                                                                                                                                   BF CS FS                               BF                                                                                                                                                                                                            BF CS FS    A3[ ]*, D4[ ]*, F4S[ ]*, D4[ ]*, B3F[ ]*, D4[ ]*, F4S[ ]*, D4                                CS FS                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               BF CS FS                               BF                                                                                                                                                                                                            BF CS FS                                                                CS FS
const int sequenceR[] = {G5, F5S, E5, E5, F5S, SS, SS , SS, RR, RR, RR , RR, RR, RR, RR , A4, G5, F5S, E5 , E5, SS, F5S, RR , RR, D5, SS, E5 , A4, RR, RR, RR , RR, RR, RR, RR , A4, E5, SS, F5S, G5, SS, SS, E5 , C5S, SS, D5, SS, SS, E5, SS, A4, A4, SS, F5S, RR , RR, RR, RR, RR , RR, RR, RR, RR , RR, G5, F5S, E5 , E5, F5S, RR, RR , RR, RR, RR, RR , RR, RR, RR, RR , A4, G5, F5S, E5 , E5, RR, RR, F5S, D5, RR, RR, E5 , A4, RR, RR, RR , RR, RR, RR, RR , RR, E5, SS, F5S, G5, SS, SS, E5, C5S, SS, SS, D5, E5, RR, A4, D5, E5, F5 , E5, D5 , C5S, RR, A4, B4F, C5, SS, F5, SS, E5, D5, D5, C5, D5, C5, C5, SS, C5, SS, A4, B4F, C5, SS, F5, SS, G5, F5, E5, D5, D5, E5, F5, SS, F5, SS, G5, A5, B5F, B5F, A5, SS, G5 , SS, F5, G5, A5, A5, G5, SS, F5, SS, D5, C5, D5, F5, F5, E5, SS, E5, F5S, F5S, A3   , A3, F3S  , F3S, A3   , A3, F3S  , F3S, A3   , A3, F3S  , F3S, A3   , A3, G5, F5S, E5, E5, SS, F5S, SS , RR, D3, SS, SS , SS, B2, SS, SS , SS, G5, F5S, E5 , E5, SS, SS, F5S, D5, SS, E5, SS , A4, SS, SS, RR , RR, D3, SS, SS , SS, E5, SS, F5S, G5, SS, SS, E5, SS, C5S, SS, D5, E5, SS, SS, A4, A4, SS, F5S, SS , RR, F3S, SS, SS , SS, B2, SS, SS , A4, G5, F5S, E5 , E5, F5S, SS, RR , RR, D3, SS, SS , SS, B2, SS, SS , A4, G5, F5S, E5 , E5, B2, SS, F5S, D5, D3, SS, E5 , A4, B2, SS, SS , SS, D3, SS, SS , SS, E5, SS, F5S, G5, SS, SS, E5, SS, C5S, SS, D5, E5, RR, A4, D5, E5, F5S, E5, D5 , C5S, RR , RR , A4 , B4F, C5, F5, SS, E5, D5, D5, C5, D5, C5, C5, SS, C5, SS, A4, B4F, C5, F5, SS, G5, F5, E5, D5, D5, E5, F5, SS, F5, G5, A5, B5F, B5F, A5, G5, F5, G5, A5, A5, G5, F5, F5 , D5, C5, D5, F5, F5, E5, SS, E5, F5S, F5S, SS, SS, RR , RR, RR , RR, RR , RR, RR, RR, RR , RR, RR , RR, RR , RR, RR, RR, RR , RR, RR , RR, RR , RR, RR, RR, RR , RR, G5, F5S, E5 , E5, SS, F5S, SS , RR, RR, RR, RR , RR, RR, RR, RR , A4, G5, F5S, E5 , E5, RR, RR, F5S, D5, RR, RR, E5 , A4, RR, RR, RR , RR, RR, RR, RR , RR, E5, SS, F5S, G5, SS, SS, E5, SS, C5S, SS, D5, E5, SS, SS, A4, A4, SS, F5S, RR , RR, RR, RR, RR , RR, RR, RR, RR , RR, G5, F5S, E5 , E5, SS, F5S, SS , RR, F3S, SS, SS , SS, D3, SS, SS , SS, G5, F5S, E5 , E5, D3, SS, F5S, D5, F3S, SS, E5 , A4, D3, SS, SS , SS, F3S, SS, SS , SS, E5, SS, F5S, G5, SS, SS, E5, SS, C5S, SS, D5, E5, RR, A4, D5, E5, F5S, E5, D5 , C5S, RR , RR , A4 , B4F, C5, F5, SS, E5, D5, D5, C5, D5, C5, C5, SS, C5, A4, B4F, C5, F5, SS, G5, F5, E5, D5, D5, E5, F5, SS, F5, G5, A5, B5F, B5F, A5, A5, G5, F5, G5, A5, A5, G5, G5, F5 , D5, C5, D5, F5, F5, E5, SS, E5, F5S, F5S, SS, SS, SS , SS, F3S, SS, A5 , A5, B5F, A5, F5S, D5, RR , E5, F5S, F5S, SS, SS, RR , RR, RR, A5, A5 , A5, B5, B5, F5S, D5, SS, E5, F5S, F5S, SS, SS, RR , RR, RR, A5, A5 , A5, B5, A5, F5S, D5, SS, E5, F5S, F5S, SS, SS, RR , RR, RR, RR, A5 , A5, B5, A5, F5 , D5, SS, E5, F5S, F5S, SS, SS, RR , RR, RR, A5, A5 , A5, B5, A5, F5S, D5, SS, F5, F5S, F5S, SS, SS, RR , RR, RR, F5S, A5 , A5, SS, SS, RR , RR, RR, G5, F5S, F5S, SS};
const int sequenceL[] = {RR, RR , RR, RR, A3 , D4, F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4 , F4S, D4, A3, D4 , F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4, B3, E4, G4 , E4, B3, E4, G4 , E4 , A3, E4, G4, E4, B3, E4, G4, E4, A3, D4 , F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4 , F4S, D4, A3 , D4, F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4 , F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4, B3, D4, G4 , D4, B3, D4, G4, D4 , A3, D4, G4, D4, A3, D4, G4, D4, B3F, D4, F4S, B4F, RR, RR, RR , F3, C4, F4, C4, G3, D4, F4, D4, A3, C4, F4, C4, F3, C4, F4, C4 , F3, C4, F4, C4, G3, D4, F4, D4, A3, C4, F4, C4, A3, C4, F4, C4, B3F, F4 , A4, F4, B3F, F4, A4, F4, A3, C4, F4, C4, A3, C4, F4, C4, A3, C4, F4, C4, A3, C4, E4 , F4S, D3   , D3, B2F  , B2F, D3   , D3, B2F  , B2F, D3   , D3, B2F  , B2F, D3   , D3, B2, SS , SS, B2, A3, D4 , F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4 , F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4, B3, E4, G4 , E4, B3, E4, G4, E4, A3 , E4, G4, E4, A3, E4, G4, E4, A3, D4 , F4S, D4, B3 , D4, F4S, D4, A3, D4, F4S, D4, B3, D4 , F4S, D4, A3 , D4, F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4 , F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4, B3, E4, G4 , E4, B3, E4, G4, E4, A3 , E4, G4, E4, A3, E4, G4, E4, F3S, SS, F3S, SS , F3S, F3S, F3S, F3S, C3, SS, C3, G3, SS, SS, G3, D3, SS, SS, D3, C3, SS, SS, C3 , C3, SS, C3, G3, SS, SS, G3, F3, SS, SS, F3, D3, SS, D3, F3 , SS , SS, G3, G3, SS, C4, SS, C4, SS, B3F, G3, SS, F3, SS, F3, SS, G3, SS, G3 , SS , A3, D4, F4S, D4, B3F, D4, F4S, D4, A3, D4, F4S, D4, B3F, D4, F4S, D4, A3, D4, F4S, D4, B3F, D4, F4S, D4, A3, D4, F4S, D4, B3, D4 , F4S, D4, A3, D4 , F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4 , F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4, B3, E4, G4 , E4, B3, E4, G4, E4, A3 , E4, G4, E4, A3, E4, G4, E4, A3, D4 , F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4 , F4S, D4, A3, D4 , F4S, D4, B3 , D4, F4S, D4, A3, D4, F4S, D4, B3, D4 , F4S, D4, A3, D4, F4S, D4, B3 , D4, F4S, D4, A3, D4, F4S, D4, B3 , D4, F4S, D4, B3, E4, G4 , E4, B3, E4, G4, E4, A3 , E4, G4, E4, A3, E4, G4, E4, F3S, SS, F3S, SS , F3S, F3S, F3S, F3S, C3, SS, C3, G3, SS, SS, G3, F3, SS, SS, F3, C3, SS, C3 , C3, SS, C3, G3, SS, SS, G3, F3, SS, SS, F3, C3, SS, C3, D3 , SS , SS, SS, G4, G4, SS, C4, SS, C4, SS, B3F, G3, SS, F3, SS, F3, SS, G3, SS, G3 , SS , A3, D4, F4S, D4, B3F, D4, F4S, D4, A3 , D4, F4S, D4, B3F, D4, F4S, D4 , A3, D4, F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4 , A3, D4, F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4 , A3, D4, F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4 , A3, D4, F4S, D4, B3, D4, F4S, D4, A3, D4, F4S, D4, B3, D4, F4S, D4 , A3, D4, F4S, D4, B3, D4 , F4S, D4, A3, D4, F4S, D4, B3, RR, RR , RR , RR};
const float beats[] =   {EN, EN , EN, EN, EN , EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN , EN , EN, EN, EN , EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN , EN, EN, EN, EN, EN, EN, EN, EN, EN, EN , EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN , EN , EN, EN , EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN , EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN, EN , EN, EN, EN, EN, EN, EN, EN, EN, EN , EN, EN , EN , QN, EN, EN , EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN , EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN , EN , EN, EN, EN , EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN , EN , QN DT, EN, QN DT, EN , QN DT, EN, QN DT, EN , QN DT, EN, QN DT, EN , QN DT, EN, EN, EN , EN, EN, EN, EN , EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN , EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN, EN, EN , EN, EN, EN, EN, EN, EN, EN, EN, EN , EN , EN, EN , EN, EN , EN, EN, EN, EN , EN, EN, EN , EN , EN, EN , EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN , EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN, EN, EN , EN, EN, EN, EN, EN, EN, EN, EN , EN, EN , EN , EN , EN , EN , EN , QN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN , QN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, QN, EN, EN, EN , EN , QN, QN, EN, EN, EN, EN, EN, EN, QN , EN, EN, EN, EN, EN, EN, EN, EN, EN , EN , EN, EN, EN , EN, EN , EN, EN , EN, EN, EN, EN , EN, EN , EN, EN , EN, EN, EN, EN , EN, EN , EN, EN , EN, EN, EN, EN , EN, EN, EN , EN , EN, EN, EN , EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN , EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN, EN, EN , EN, EN, EN, EN, EN, EN, EN, EN, EN , EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN , EN , EN, EN, EN , EN , EN, EN , EN, EN , EN, EN, EN, EN , EN, EN, EN , EN , EN, EN, EN, EN , EN, EN , EN, EN , EN, EN, EN, EN , EN, EN , EN, EN , EN, EN, EN, EN , EN, EN, EN, EN, EN, EN , EN, EN, EN, EN, EN, EN, EN, EN , EN, EN , EN , EN , EN , EN , EN , QN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, QN, EN, EN , QN, EN, EN, EN, EN, EN, EN, EN, EN, EN, EN, QN, EN, EN, EN , EN , EN, EN, QN, EN, EN, EN, EN, EN, EN, QN , EN, EN, EN, EN, EN, EN, EN, EN, EN , EN , EN, EN, EN , EN, EN , EN, EN , EN, EN , EN, EN , EN, EN , EN, EN , EN , EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN , EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN , EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN , EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN, EN, EN, EN , EN , EN, EN, EN , EN, EN, EN , EN , EN, EN, EN, EN , EN, EN, EN, EN , EN , QN};
const int length = sizeof(beats) / sizeof(int);

int main(void)
{
    wiringPiSetup();
    softToneCreate(LEFT_CHANNEL);
    softToneCreate(RIGHT_CHANNEL);
    for (int i = 0; i < length; i++)
    {
        if (sequenceL[i] != SS) {
            softToneWrite(LEFT_CHANNEL, sequenceL[i]);
        }
        if (sequenceR[i] != SS) {
            softToneWrite(RIGHT_CHANNEL, sequenceR[i]);
        }
        delay(60000 / bpm * beats[i]);
        if (sequenceL[i+1] != SS) {
            softToneWrite(LEFT_CHANNEL, LOW);
        }
        if (sequenceR[i+1] != SS) {
            softToneWrite(RIGHT_CHANNEL, LOW);
        }
        delay(8);
    };
    return 0;
}