#!/bin/sh
cbversion=$(head -n 1 /etc/cb/VERSION)

if [ "$(systemctl is-active ssh.service)" = "active" ]; then
  sshstatus="   \e[92mOK\e[39m   "
elif [ "$(systemctl is-enabled ssh.service)" = "disabled" ]; then
  sshstatus="\e[91mDISABLED\e[39m"
elif [ "$(systemctl is-failed ssh.service)" = "failed" ]; then
  sshstatus=" \e[91mFAILED\e[39m "
else
  sshstatus="\e[93mSTOPPED\e[39m "
fi


if [ "$(systemctl is-active vncserver-x11-serviced.service)" = "active" ]; then
  vncstatus="   \e[92mOK\e[39m   "
elif [ "$(systemctl is-enabled vncserver-x11-serviced.service)" = "disabled" ]; then
  vncstatus="\e[91mDISABLED\e[39m"
elif [ "$(systemctl is-failed vncserver-x11-serviced.service)" = "failed" ]; then
  vncstatus=" \e[91mFAILED\e[39m "
else
  vncstatus="\e[93mSTOPPED\e[39m "
fi

if [ -f /etc/cb/CBFi/.BRIDGE_ENABLED ]; then
  bridgestatus="   \e[92mOK\e[39m   "
else
  bridgestatus="\e[91mDISABLED\e[39m"
fi

if [ -f /etc/cb/CBFi/.ENABLED ]; then
  cbfistatus="   \e[92mOK\e[39m   "
  bdip=$(/sbin/ifconfig br0 | grep 'inet ' | awk '{print $2}')
  bsip=$(/sbin/ifconfig br0:1 | grep 'inet ' | awk '{print $2}')
elif [ -f /etc/cb/CBFi/.CLIENTMODE ]; then
  cbfistatus=" \e[93mCLIENT\e[39m "
else
  cbfistatus="\e[91mDISABLED\e[39m"
fi

if ping -q -c 1 -W 1 8.8.8.8 >/dev/null 2>/dev/null; then
  intstatus="   \e[92mOK\e[39m   "
  if ping -q -c 1 -W 1 google.com >/dev/null; then
    dnsstatus="   \e[92mOK\e[39m   "
    eip=$(curl -s ipecho.net/plain)
  else
    dnsstatus=" \e[91mFAILED\e[39m "
    eip=""
  fi
else
  intstatus=" \e[91mFAILED\e[39m "
  dnsstatus=" \e[91mFAILED\e[39m "
  eip=""
fi

/etc/cb/UBUBOT/arduino/handshake
arduinoresponse=$?
if [ $arduinoresponse -eq 0 ]; then
  arduinostatus="   \e[92mOK\e[39m   "
elif [ $arduinoresponse -eq 2 ]; then
  arduinostatus="\e[93mOUTDATED\e[39m"
else
  arduinostatus=" \e[91mFAILED\e[39m "
fi

pip=$(/sbin/ifconfig wlan0 | grep 'inet ' | awk '{print $2}')

echo
echo "\e[38;5;18m######\e[38;5;19m######\e[38;5;20m######\e[38;5;21m######\e[38;5;21m######\e[38;5;20m######\e[38;5;19m######\e[38;5;18m######\e[39m"
echo "\e[38;5;18m#\e[39m           \e[48;5;17;95mCyberBoysPi - $cbversion\e[49;39m            \e[38;5;18m#"
echo "\e[38;5;18m######\e[38;5;19m######\e[38;5;20m######\e[38;5;21m######\e[38;5;21m######\e[38;5;20m######\e[38;5;19m######\e[38;5;18m######\e[39m"
echo "\e[38;5;18m#\e[39m             \e[96mSSH\e[39m     -  $sshstatus              \e[38;5;18m#"
echo "\e[38;5;18m#\e[39m             \e[96mVNC\e[39m     -  $vncstatus              \e[38;5;18m#"
echo "\e[38;5;18m#\e[39m             \e[96mCBFi\e[39m    -  $cbfistatus              \e[38;5;18m#"
echo "\e[38;5;18m#\e[39m            \e[96mCBFiB\e[39m    -  $bridgestatus              \e[38;5;18m#"
echo "\e[38;5;18m#\e[39m           \e[96mInternet\e[39m  -  $intstatus              \e[38;5;18m#"
echo "\e[38;5;18m#\e[39m             \e[96mDNS\e[39m     -  $dnsstatus              \e[38;5;18m#"
echo "\e[38;5;18m#\e[39m           \e[96mArduino\e[39m   -  $arduinostatus              \e[38;5;18m#"
echo "\e[38;5;18m######\e[38;5;19m######\e[38;5;20m######\e[38;5;21m######\e[38;5;21m######\e[38;5;20m######\e[38;5;19m######\e[38;5;18m######\e[39m"
echo "\e[38;5;18m#\e[39m    \e[48;5;17;95m@author Roderick D. - github.com/rorik\e[49;39m    \e[38;5;18m#"
echo "\e[38;5;18m######\e[38;5;19m######\e[38;5;20m######\e[38;5;21m######\e[38;5;21m######\e[38;5;20m######\e[38;5;19m######\e[38;5;18m######\e[39m"
echo
if [ ! -z $pip ]; then echo "Private IP: $pip"; fi
if [ ! -z $eip ]; then echo "External IP: $eip"; fi
if [ ! -z $bdip ]; then echo "Bridge DHCP IP: ${bdip}"; fi
if [ ! -z $bsip ]; then echo "Bridge static IP: $bsip"; fi
echo "Device: $(cat /sys/firmware/devicetree/base/model)"
